# Generated by Django 5.1.7 on 2025-04-01 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('servico', models.CharField(choices=[('montagem_pc', 'Montagem de PC Gamer'), ('limpeza_pc', 'Limpeza de PC Gamer'), ('orcamento_basico', 'Orçamento Básico'), ('organizacao_setup', 'Organização de Setup'), ('consultoria_setup', 'Consultoria de Setup'), ('agendamento_empresarial', 'Agendamento Empresarial')], max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamentos.cliente')),
            ],
        ),
    ]
